### ISSUE TITLE
 FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Dell EMC OMSDK library is required for this module"}

### ISSUE THREAD

**Issue by cloudriders2021** [jonas-werner/ansible-playbooks#1]
Hi Jonas,

First of all, I like to thank you for all the video and tutorials you contribute on the youtube., it helped me a lot :-) 

 I am hoping you can help me with this dell specific issue with OMSDK ?  for some reasons my ansible refuse to see the omsdk when running any of the dell playbooks. i have installed based off your instructions. 
I am running 

Ubuntu 18
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/j2/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/j2/.local/lib/python3.8/site-packages/ansible
  executable location = /home/j2/.local/bin/ansible
  python version = 3.8.2 (default, Feb 26 2020, 02:56:10) [GCC 7.4.0]

Python 3.8.2
omsdk-1.2.434._-py2.py3-none-any.whl installed under /etc/ansible/omsdk...

 thanks much!!

**Comment by jonas-werner** [comment]
Hi there, 
Thank you for your kind words. I'm happy to hear that it was helpful. 

This sure sounds like an environment issue. 

1. I presume you weren't using a virtual environment (python3 -m venv or virtualenv) while installing the OMSDK so it was associated with a python installation in a different location? 

2. You're running it as the user which installed the modules? Not as root directly or via "su"? If you're using "su" try using "su -p" to preserve the environment of the user under which you installed OMSDK. 

3. Are you executing ansible-playbook directly or via Jenkins or another external app? That may cause the environment not to be loaded properly. In Jenkins there's an option to "become" a specific user during playbook execution if that helps. 

4. What is the output of ansible-doc -l | egrep -i "dell" ? Just to check what plugins you have installed.

**Comment by cloudriders2021** [comment]
thank you so much Jonas,
I got it working by issuing playbook with become-user as you suggested and that took care of the environment issue : 
ap 2.yml --become-user j2 -vvv

I can now have a good night sleep. :-) 

please keep up with your posting,  your instructional video beats reading thousand pages of Dell cryptic white papers !!

Dōmo arigatōgozaimasu !!

**Comment by jonas-werner** [comment]
Excellent, happy to hear that it works :)
Thank you! Yeah, I'll continue to do my best at providing content that is useful. 
All the best,
Jonas
